# Generated by Django 3.2.16 on 2023-01-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221217_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogpost',
        ),
    ]
